[package]
name = "rddns"
version = "0.1.0"
authors = ["Raik Bieniek <dev@voidnode.de>"]

[dependencies]
hyper = "0.11.2"
hyper-tls = "0.1.2"
futures = "0.1.17"
tokio-core = "0.1.11"
toml = "0.4.5"
serde = "1.0.27"
serde_derive = "1.0.27"
regex = "0.2"
lazy_static = "1.0.0"
log = "0.4.0"
simplelog = "0.5.1"

[dev-dependencies]
tempdir = "0.3.5"